storage_class: Standard_LRS
virtual_network_cidr: 192.168.33.0/24
username: "ansible"
password: "Password1!"


topology:
  virtual_machines:
    - vm_name: tower
      vm_size: Standard_D2_v3
      vm_ip_address: "192.168.33.51"
      vm_security_group: "sg-linux"
      vm_image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.4'
        version: latest

    - vm_name: linux1
      vm_size: Standard_D2_v3
      vm_ip_address: "192.168.33.101"
      vm_security_group: "sg-linux"
      vm_image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.4'
        version: latest

    - vm_name: desktop
      vm_size: Standard_D2_v3
      vm_ip_address: "192.168.33.50"
      vm_security_group: "sg-windows"
      vm_image:
        publisher: "MicrosoftWindowsServer"
        offer: "WindowsServer"
        sku: "2016-Datacenter"
        version: "latest"

    - vm_name: windows1
      vm_size: Standard_D2_v3
      vm_ip_address: "192.168.33.201"
      vm_security_group: "sg-windows"
      vm_image:
        publisher: "MicrosoftWindowsServer"
        offer: "WindowsServer"
        sku: "2016-Datacenter"
        version: "latest"




linux_vm_size: Standard_D2_v3
linux_ip_address: "192.168.33.51"
linux_vm_image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.4'
      version: latest

windows_vm_size: Standard_D2_v3
windows_ip_address: "192.168.33.50"
windows_vm_image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.4'
      version: latest


ansible_tower_install: false
ansible_tower_basename: "ansible-tower-setup"
ansible_tower_version: "3.5.1-1"
ansible_tower_archive: "{{ ansible_tower_basename }}-{{ ansible_tower_version }}.tar.gz"
ansible_tower_release_url: "http://releases.ansible.com/ansible-tower/setup/{{ ansible_tower_archive }}"
ansible_tower_password: "ansible"

azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID')}}"
azure_tenant: "{{ lookup('env', 'AZURE_TENANT')}}"
azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
azure_secret: "{{ lookup('env', 'AZURE_SECRET')}}"

default_security_rules_windows:
  - name: RDP
    protocol: Tcp
    destination_port_range: 3389
    access: Allow
    priority: 102
    direction: Inbound
  - name: WINRM
    protocol: Tcp
    destination_port_range: 5985
    access: Allow
    priority: 105
    direction: Inbound

default_security_rules_linux:
  - name: SSH
    protocol: Tcp
    destination_port_range: 22
    access: Allow
    priority: 101
    direction: Inbound
  - name: HTTP
    protocol: Tcp
    destination_port_range: 80
    access: Allow
    priority: 103
    direction: Inbound
  - name: HTTPS
    protocol: Tcp
    destination_port_range: 443
    access: Allow
    priority: 104
    direction: Inbound
