---
- name: Create Azure Ansible Lab
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - import_tasks: "tasks/check_variables.yaml"
  
  tasks:
    - import_tasks: "tasks/create_azure_environment.yaml"
      tags:
        - create_azure_env

    - import_tasks: "tasks/create_security_groups.yaml"
      vars:
        name: "sg-windows"
        rules: "{{ default_security_rules_windows }}"
      tags:
        - create_azure_env

    - import_tasks: "tasks/create_security_groups.yaml"
      vars:
        name: "sg-linux"
        rules: "{{ default_security_rules_linux }}"
      tags:
        - create_azure_env
    
    - name: "Create virtual machines from the topology object"
      include_tasks: "tasks/create_vm.yaml"
      with_items: "{{ topology.virtual_machines }}"
      vars:
        vm_name: "{{ item.vm_name }}"
        os_type: "{{ item.os_type }}"
        vm_ip_address: "{{ item.vm_ip_address }}"
        vm_security_group: "{{ item.vm_security_group }}"
        vm_image: "{{ item.vm_image }}"
        vm_size: "{{ item.vm_size }}"
        vm_subnet: "sn{{ lab_id }}"
        vm_virtual_network: "vn{{ lab_id }}"
        vm_ssh_public_keys: "{{ item.vm_ssh_public_keys | default(omit) }}"

    - name: "Install Ansible Tower"
      when: ansible_tower_install
      import_tasks: "tasks/tower_install.yaml"

    - name: "Install Windows Desktop"
      when: windows_desktop_install
      import_tasks: "tasks/windows_desktop_install.yaml"


#
# Create a local file with the information
#
    - name: Add entry to lab_id.txt
      tags:
        - always
      copy:
        dest: "{{ lab_id }}.txt"
        content: |
          Lab {{ lab_id }}
          Windows machine ip is {{ windows_desktop_ip_address }} you can now RDP to it.
          Tower url is {{ ansible_tower_url }}
