---
- name: Development playbook for testing features
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    res_group: pod1

    storage_class: Standard_LRS
    virtual_network_cidr: 192.168.33.0/24
    username: "ansible"
    password: "Password1!"
    
    ansible_tower_install: false
    ansible_tower_basename: "ansible-tower-setup"
    ansible_tower_version: "3.5.1-1"
    ansible_tower_archive: "{{ ansible_tower_basename }}-{{ ansible_tower_version }}.tar.gz"
    ansible_tower_release_url: "http://releases.ansible.com/ansible-tower/setup/{{ ansible_tower_archive }}"
    ansible_tower_password: "ansible"

    azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID')}}"
    azure_tenant: "{{ lookup('env', 'AZURE_TENANT')}}"
    azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
    azure_secret: "{{ lookup('env', 'AZURE_SECRET')}}"
  
  tasks:

    - set_fact:
        vm_name: "tower"
    
    - name: Get facts for VM {{ vm_name }}
      azure_rm_virtualmachine:
        client_id: "{{ azure_client_id }}"
        tenant: "{{ azure_tenant }}"
        subscription_id: "{{ azure_subscription_id }}"
        secret: "{{ azure_secret }}"
        resource_group: "{{ res_group }}"
        name: "{{ vm_name }}"
      register: vm_facts
    
    - debug:
        var: vm_facts

    - debug:
        msg: "{{ vm_facts.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
