---
- name: Development playbook for testing features
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    res_group: lab
    storage_class: Standard_LRS
    virtual_network_cidr: 192.168.33.0/24
    username: "ansible"
    password: "Password1!"
    centos_vm_size: Standard_D2_v3
    centos_ip_address: "192.168.33.51"
    windows_vm_size: Standard_D2_v3
    windows_ip_address: "192.168.33.50"
    ansible_tower_install: false
    ansible_tower_basename: "ansible-tower-setup"
    ansible_tower_version: "3.5.1-1"
    ansible_tower_archive: "{{ ansible_tower_basename }}-{{ ansible_tower_version }}.tar.gz"
    ansible_tower_release_url: "http://releases.ansible.com/ansible-tower/setup/{{ ansible_tower_archive }}"
    ansible_tower_password: "ansible"

    azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID')}}"
    azure_tenant: "{{ lookup('env', 'AZURE_TENANT')}}"
    azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
    azure_secret: "{{ lookup('env', 'AZURE_SECRET')}}"
  
  tasks:

    - name: "Check if there is a license file available on the current directory"
      local_action: stat path=ansible_license.json
      register: ansible_license_check

    - debug:
        var: ansible_license_check

    - set_fact:
        tower_url: "https://13.92.199.83/"

    - name: "Install the Tower license using API"
      when: ansible_license_check.stat.exists
      uri:
        url: "{{ tower_url }}api/v2/config/"
        body_format: json
        src: "ansible_license.json"
        url_username: "admin"
        url_password: "{{ ansible_tower_password }}"
        force_basic_auth: yes
        method: "POST"
        validate_certs: no
      register: tower_add_license

    - debug:
        var: tower_add_license